docs: optimize the docs and fix small errors / typos
cloudogu/dogu-development-docs pull request #45
Opened 2023-05-30 05:56 UTC by meiserloh

2023-06-12 07:49 UTC, robertauer requested changes

2023-06-13 08:15 UTC, meiserloh commented on docs/additional/internal_aspects_en.md
> +└ └── how_to_build_a_plugin.md
done

2023-06-13 08:16 UTC, meiserloh commented on docs/core/basics_en.md
> +  This will cause the new dogu to appear in the warp menu (along with the `warp`-tag in the dogu.json).
:heavy_check_mark:

2023-06-13 08:16 UTC, meiserloh commented on docs/additional/interesting_aspects_en.md
> +[healthcheck]: https://github.com/cloudogu/sonar/blob/8e389605d1f2fa7720d725a1cca6692f4c6b77e3/Dockerfile#L41
:heavy_check_mark:

2023-06-13 08:16 UTC, meiserloh commented on docs/core/compendium_en.md
> +The dogu namespace allows to regulate access to dogus in that namespace. There are three reserved dogu namespaces: The namespaces `official` and `k8s` are open to all users without any further costs.
:heavy_check_mark:

2023-06-15 12:17 UTC, merged